Style/MutableConstant:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

RSpec/LetSetup:
  Enabled: false
